### ISSUE TITLE
Quick thoughts

### ISSUE THREAD

**Issue by ocornut** [fabioarnold/TwoTriangles#1]
Nice project. It could be very useful to play with shaders without the constraints of webgl.

As a quick suggestion, you may want to have a toggle to switch between "fullscreen" and "tools" mode. The fullscreen mode would show only the shader in as much space as possible without any ui, whereas "tools" mode would show the shader result in a resizable window. (There is a way to specify constraints in imgui if you need to enforce a specific ratio). Map the toggle on say, the F key for quick switch.

You might also provide an _optional_ embedded source editor using InputTextMultiline(). I agree that using external editor makes more sense in most cases but it's also nice to have a backup plan for quick hackery (tho you may find the imgui one lacking).

**Comment by ocornut** [comment]
You might also want to provide an explicit link from the github toward to the Releases section where binaries are available. Because binaries aren't so common in github, and for end-users who aren't github users it would make sense ihmo.

**Comment by fabioarnold** [comment]
Thanks for your swift feedback! :)
I really like the idea of having a sort of fullscreen "presentation" mode for shaders. Also a simple built-in text editor couldn't hurt I agree.
I added a Windows section to the README with a link to the releases tab.

Again thank you very much for creating dear imgui. I use it in almost every project! :)

**Comment by fabioarnold** [comment]
* Hotkeys for toggling GUI and fullscreen mode have been added in c54ebb9186ce7418824c221e3cc50b6a77f315ef
* A basic source editor has been added in fd6ab344b4a1a12b120e8884634c3ddd5ca3c584
* A link to the releases tab has been added to README.md in 8c5160d38b55a267f619a9046befe5c38a407822 (I should probably create a build of a more recent version)

➡️ Closing

Thanks again for making these suggestions! :)

**Comment by ocornut** [comment]
Wow that was quite unexpected :)

If you want a more full featured text editor in, you may use this one:
https://github.com/BalazsJako/ImGuiColorTextEdit

**Comment by fabioarnold** [comment]
Yeah, sure is after 1.5 years. 😅

As you said yourself the basic editor is for quick hackery. We don't want to encourage anyone. ;) It's bring your favourite text editor and live reload on file changes.

Though this looks great and seams easy enough to integrate. I'll open a separate issue for that.

Thanks!
