### ISSUE TITLE
OneTriangle mode? :)

### ISSUE THREAD

**Issue by nlguillemot** [fabioarnold/TwoTriangles#4]
Instead of drawing two triangles, you could draw just one:

```
|   \
|      \
|         \
|           \
| _ _ _ _ _   \
|  screen   |   \
| _ _ _ _ _ | _ _ \
```

this can actually make a noticeable performance difference, since 2 triangles split the screen in half which causes pixels along the diagonal to be scheduled in a non-optimal way.

**Comment by fabioarnold** [comment]
I couldn't find any references to that except for this discussion here: https://www.opengl.org/discussion_boards/showthread.php/175492-FXAA-and-Fullscreen-Triangles and their explanations make sense to me for squeezing out a little more performance.
Sadly it kind of defeats the name I chose. 😂
I actually had a look at what the shadertoy guys are doing and they're drawing a unit quad. So this feature could give this little program a tiny edge. 😁

**Comment by nlguillemot** [comment]
Testing the difference of performance between two triangles vs one triangle would be an interesting experiment!

**Comment by fabioarnold** [comment]
After 1.5 years I implemented single triangle mode and made it default in b8790b953d3d9f0141ddecd9fdd72097f01ca62d. Never say never. :)
